service: ausfin-api

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2

plugins:
  - serverless-wsgi

functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

    environment:
      hello: world

package:
  exclude:
    - node_modules/**
    - env/**

custom:
  wsgi:
    app: ausfin.wsgi.application
    pythonBin: python
