# Generated by Django 2.0.3 on 2018-04-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='balanceevent',
            name='balance_update',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='balance.BalanceUpdate'),
            preserve_default=False,
        ),
    ]
